import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Select } from "./_components/Select"
import { Tab } from "./_components/Tab"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Tab>{children}</Tab>
            </body>
        </html>
    )
}
